### ISSUE TITLE
Validation is executed on disabled fields (Angular)

### ISSUE THREAD

**Issue by pennal** [six-group/six-webcomponents#196] opened 2024-02-06 15:56 UTC
### Six Webcomponents version

4.0.3

### Steps to reproduce

Simple example:

form.component.ts
```
testForm = this.fb.group({
    testInput: ['', [Validators.required, Validators.minLength(2)]],
  });

submitTestForm(event: SubmitEvent) {
    console.log('valid:', this.testForm.valid);
  }

```

form.component.html
```
<form [formGroup]="testForm" sixForm (sixSubmit)="submitTestForm($event)">
  <six-input label="test input" type="text" formControlName="testInput" required></six-input>
  <six-button submit>Submit Test</six-button>
</form>
<six-button (click)="testForm.controls.testInput.disabled ? testForm.controls.testInput.enable() : testForm.controls.testInput.disable()">Toggle</six-button>
```

returns in the console:
```
valid: false
```

### What is expected?

Whenever a form control is disabled, the validation should not be executed.

### What is actually happening?

Validation is executed regardless of state

**Comment by ibirrer** [comment] 2024-02-06 16:52
This behavior is expected due to how Angular forms work.

If all form controls within a form are disabled, Angular considers the entire form as disabled, and no validation checks are performed and the `valid` field is set to `false`. It's important to note that a form can have one of several statuses: VALID, INVALID, PENDING, or DISABLED.

In the example provided above, the form is in the status DISABLED, if the input field is disabled. 

Therefore, in your scenario, you should check the status of the form using `this.testForm.status` rather than relying on the `valid` property.

**Comment by FabianKueng** [comment] 2024-02-07 14:08
To clarify: The problem is not regarding the status of the FormGroup/FormControl, it is how the SIX web components handle the disabling of a FormControl/FormGroup and the following validation of those FormControls/FormGroups.

The ControlValueAccessors implemented by the SIX web components do not take into account if a control is disabled and show the error message regardless.
Angular handles this differently, if a control is disabled in Angular, it is extempt from validation and therefore doesn't show an error message: https://angular.io/api/forms/AbstractControl#disable 

IMO we should handle this the same way to be in line with Angular validation. I will reopen this issue and provide a fix for this.

**Closed** 2024-02-08 08:41 UTC
